import js from '@eslint/js';
import globals from 'globals';

const gameGlobals = {
    // constants.js
    canvas: 'readonly',
    ctx: 'writable',
    staticLayer: 'writable',
    TILE_SIZE: 'readonly',
    GRID_COLS: 'readonly',
    GRID_ROWS: 'readonly',
    TILE_CENTER_OFFSET: 'readonly',
    TOWER_DRAW_BASE: 'readonly',
    TOWER_PICK_RADIUS: 'readonly',
    ENEMY_RADIUS: 'readonly',
    ENEMY_BASE_HP: 'readonly',
    ENEMY_HP_GROWTH_RATE: 'readonly',
    ENEMY_SPEED: 'readonly',
    ENEMY_BASE_REWARD: 'readonly',
    TOWER_UPGRADE_BASE_COST: 'readonly',
    TOWER_DAMAGE_GROWTH: 'readonly',
    TOWER_UPGRADE_COST_MULTIPLIER: 'readonly',
    TOWER_MAX_LEVEL: 'readonly',
    WAVE_CLEAR_BONUS_BASE: 'readonly',
    WAVE_CLEAR_BONUS_PER_WAVE: 'readonly',
    WAVE_MAX: 'readonly',
    DEFAULT_TOWER_TYPE: 'readonly',
    AUTOCOLLAPSE_WIDTH: 'readonly',
    prefersReducedMotion: 'writable',
    ENEMY_TYPE_DEFINITIONS: 'readonly',
    ENEMY_TYPE_MAP: 'readonly',
    TARGET_PRIORITIES: 'readonly',
    gameState: 'readonly',

    // towers.js
    TOWER_TYPES: 'readonly',
    TOWER_ORDER: 'readonly',

    // utils.js
    TOWER_SELECTOR_BUTTONS: 'writable',
    gridFromPosition: 'readonly',
    keyFromGrid: 'readonly',
    getTowerDefinition: 'readonly',
    darkenHex: 'readonly',
    getColorFromArray: 'readonly',
    getTowerColor: 'readonly',
    getProjectileColor: 'readonly',
    hexToRgba: 'readonly',
    alphaCache: 'readonly',
    ALPHA_CACHE_MAX: 'readonly',
    applyAlpha: 'readonly',
    lerpAngle: 'readonly',
    formatNumber: 'readonly',
    calculateTowerDamage: 'readonly',
    calculateUpgradeCost: 'readonly',
    recalcTowerStats: 'readonly',

    // map.js
    MAP_DEFINITIONS: 'readonly',
    activeMapId: 'writable',
    waypoints: 'writable',
    pathTiles: 'writable',
    buildMapData: 'readonly',

    // ui.js
    towers: 'readonly',
    towerPositionSet: 'readonly',
    enemies: 'readonly',
    projectiles: 'readonly',
    impactEffects: 'readonly',
    muzzleFlashes: 'readonly',
    kbCursor: 'writable',
    kbCursorActive: 'writable',
    _longPressTimer: 'writable',
    _longPressFired: 'writable',
    _touchStartX: 'writable',
    _touchStartY: 'writable',
    LONG_PRESS_DURATION: 'readonly',
    LONG_PRESS_MOVE_THRESHOLD: 'readonly',
    NUMBER_FORMAT: 'readonly',
    GOLD_LABEL: 'readonly',
    LIVES_LABEL: 'readonly',
    WAVE_LABEL: 'readonly',
    GOLD_INPUT: 'readonly',
    GOLD_APPLY_BUTTON: 'readonly',
    GOLD_ADJUST_BUTTONS: 'readonly',
    TOWER_STATS_PANEL: 'readonly',
    ENEMY_STATS_PANEL: 'readonly',
    TOWER_STATS_FIELDS: 'readonly',
    ENEMY_STATS_FIELDS: 'readonly',
    SPEED_BUTTONS: 'readonly',
    WAVE_INPUT: 'readonly',
    WAVE_APPLY_BUTTON: 'readonly',
    WAVE_PREVIEW_PANEL: 'readonly',
    WAVE_PREVIEW_FIELDS: 'readonly',
    DEFEAT_OVERLAY: 'readonly',
    RETRY_BUTTON: 'readonly',
    CANCEL_RETRY_BUTTON: 'readonly',
    MAP_SELECT_OVERLAY: 'readonly',
    MAP_LIST_CONTAINER: 'readonly',
    START_GAME_BUTTON: 'readonly',
    BUILD_PANEL: 'readonly',
    BUILD_TOGGLE: 'readonly',
    BUILD_CONTAINER: 'readonly',
    TOWER_LIST_CONTAINER: 'readonly',
    SOUND_TOGGLE: 'readonly',
    A11Y_ANNOUNCER: 'readonly',
    SELECTED_TOWER_INDICATOR: 'readonly',
    UPGRADE_TOWER_BUTTON: 'readonly',
    SELL_TOWER_BUTTON: 'readonly',
    TARGET_PRIORITY_SELECT: 'readonly',
    announceQueue: 'readonly',
    announceProcessing: 'writable',
    processAnnounceQueue: 'readonly',
    announce: 'readonly',
    updateGoldUI: 'readonly',
    hideTowerStats: 'readonly',
    hideEnemyStats: 'readonly',
    hideAllStats: 'readonly',
    setSelectedTowerButton: 'readonly',
    populateTowerList: 'readonly',
    buildPanelCollapsed: 'writable',
    buildPanelUserOverride: 'writable',
    setBuildPanelCollapsed: 'readonly',
    getWaveEnemyCount: 'readonly',
    getWaveEnemyStats: 'readonly',
    updateWavePreview: 'readonly',
    updateSpeedControls: 'readonly',
    setGameSpeed: 'readonly',
    setTextIfChanged: 'readonly',
    updateTowerStatsFields: 'readonly',
    updateEnemyStatsFields: 'readonly',

    // audio.js
    audioContext: 'writable',
    masterGain: 'writable',
    soundMuted: 'writable',
    audioContextCreating: 'writable',
    ensureAudioContext: 'readonly',
    playToneSequence: 'readonly',
    cachedNoiseBuffer: 'writable',
    cachedNoiseDuration: 'writable',
    playNoise: 'readonly',
    SOUND_LIBRARY: 'readonly',
    updateSoundToggle: 'readonly',
    setSoundMuted: 'readonly',
    playSound: 'readonly',

    // game.js
    clearCurrentWave: 'readonly',
    ensureTowerMetadata: 'readonly',
    setWave: 'readonly',
    damageEnemyAtIndex: 'readonly',
    damageEnemy: 'readonly',
    spawnMuzzleFlash: 'readonly',
    spawnImpactEffect: 'readonly',
    applyExplosion: 'readonly',
    showTowerStats: 'readonly',
    showEnemyStats: 'readonly',
    getAdjustedPickRadius: 'readonly',
    getTowerAtPoint: 'readonly',
    getEnemyAtPoint: 'readonly',
    upgradeTower: 'readonly',
    sellTower: 'readonly',
    flashGoldInsufficient: 'readonly',
    _defeatPreviousFocus: 'writable',
    showDefeatDialog: 'readonly',
    hideDefeatDialog: 'readonly',
    _mapSelectPreviousFocus: 'writable',
    showMapSelectOverlay: 'readonly',
    hideMapSelectOverlay: 'readonly',
    populateMapList: 'readonly',
    resetGame: 'readonly',
    startWave: 'readonly',
    canBuildAt: 'readonly',
    createTowerData: 'readonly',
    pickEnemyType: 'readonly',
    spawnEnemy: 'readonly',
    findTarget: 'readonly',
    _findTargetResult: 'readonly',
    spawnProjectile: 'readonly',
    handleTowerFireVisuals: 'readonly',
    attackShotgun: 'readonly',
    attackBeam: 'readonly',
    attackBurst: 'readonly',
    attackExplosive: 'readonly',
    attackMortar: 'readonly',
    attackDefault: 'readonly',
    ATTACK_PATTERNS: 'readonly',
    performTowerAttack: 'readonly',
    handleLaserAttack: 'readonly',
    update: 'readonly',

    // renderer.js
    drawGrid: 'readonly',
    drawPath: 'readonly',
    buildStaticLayer: 'readonly',
    drawHexagon: 'readonly',
    drawTowerShape: 'readonly',
    drawTowers: 'readonly',
    drawEnemies: 'readonly',
    drawProjectileTrail: 'readonly',
    drawImpactEffects: 'readonly',
    drawLaserBeams: 'readonly',
    drawMuzzleFlashes: 'readonly',
    drawProjectiles: 'readonly',
    initKbCursor: 'readonly',
    moveKbCursor: 'readonly',
    activateKbCursor: 'readonly',
    drawHover: 'readonly',
    drawState: 'readonly',
    render: 'readonly',

    // main.js
    _cachedCanvasRect: 'writable',
    updateCanvasRect: 'readonly',
    getCanvasCoords: 'readonly',
    _hoverTileObj: 'readonly',
    handlePointerMove: 'readonly',
    handlePointerDown: 'readonly',
    elapsedTime: 'writable',
    lastTime: 'writable',
    rafHandle: 'writable',
    loopErrorCount: 'writable',
    renderDirty: 'writable',
    markRenderDirty: 'readonly',
    MAX_LOOP_ERRORS: 'readonly',
    loop: 'readonly',
    stopLoop: 'readonly',
    startLoop: 'readonly'
};

export default [
    js.configs.recommended,
    {
        files: ['*.js'],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'script',
            globals: {
                ...globals.browser,
                ...gameGlobals
            }
        },
        rules: {
            'no-undef': 'warn',
            'no-unused-vars': 'warn',
            'no-redeclare': 'warn'
        }
    },
    {
        files: ['tests/**/*.js', 'scripts/**/*.js'],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'commonjs',
            globals: {
                ...globals.node,
                ...gameGlobals
            }
        },
        rules: {
            'no-undef': 'warn',
            'no-unused-vars': 'warn',
            'no-redeclare': 'warn'
        }
    },
    {
        ignores: ['node_modules/**', '.husky/**']
    }
];
